### PR TITLE
Betamax tests

### PR DESCRIPTION
**Pull request by cowboygneox**
Attempting to fix the issues with the PR #18. Let's see if this works

### CODE REVIEW

**Comment by walro** [comment]
@cowboygneox any news? :)

**Comment by cowboygneox** [comment]
@walro I know it's been on and off for me, but every time I'm on, I'm making progress. I'm in-between contracts now, so once I catch up a little bit more, I should have plenty of time to get on top of Betamax.

**Comment by walro** [comment]
Alright, thanks for getting back to me (us)!

**Comment by cowboygneox** [comment]
@walro This is what I'm working on today. I'll report anything I learn as I go.

**Comment by cowboygneox** [comment]
After some digging, I'm seeing a `SecureRandom` likely due to the Docker image. I'm not sure how to fix it yet, but I have some experience fighting this issue. Let's see what I can do.

**Comment by cowboygneox** [comment]
I'm quite convinced it's a `SecureRandom` issue, but I'm not sure what to do about it yet.

**Comment by cowboygneox** [comment]
@walro So when I ran without docker, it passed on the Oracle JVM's. I'm not sure why the OpenJDK crashed, but it could be a fluke. I'm going to continue to try and figure out what Docker does to make this not work.

**Comment by walro** [comment]
Awesome, thanks for the update!

We had [troubles with OpenJDK7](https://travis-ci.org/twingly/twingly-search-api-java/jobs/113609524) in the very first Travis test run, but we just switched over to contained-based builds and never looked back :)

**Comment by cowboygneox** [comment]
@walro I'm a huge supporter of Docker, but I'm sure this issue comes down to entropy for the random. Even providing a `-D` to change the random loader still doesn't fix the issue. The JVM must not obey that in all places (probably for good reason when it comes to SSL). I'm still working on it.

**Comment by cowboygneox** [comment]
@walro I emailed Travis asking if there's something they recommend for increasing entropy on the Docker containers. For today, I've done all I can, but I'll keep on top of it.

I will be sure to document this issue and solution in length when we finally get to the end of it.

**Comment by cowboygneox** [comment]
@walro Ok, TravisCI and I have confirmed that it's not a `/dev/random` issue, which leaves only one alternative: I have to completely change how we're doing MITM proxies. What I'll likely do (but I need to give it some thought) is ask users of Betamax to install a Betamax certificate as a CA into their CI's (ex. TravisCI) cacerts. Then, when we generate certs for any address, the JVM will implicitly trust them. It would be easier to document and support installing a single certificate rather than generate a certificate per site, which may be messy.

All I can right now is that I'm super tired today and I need some time to think and get the motivation to do what will certainly be an unpleasant refactor. I want to make sure I do this right so I never have to again.

If you or your team have any ideas for how to make working with SSL certificates easier, I would love to hear them. No matter what, though, I believe we're going to have to stage the environment in some way prior to running the JVM, as the JVM does not like us messing with trust stores and certs from within the JVM (gee, I wonder why it wouldn't like that...).

I'll keep you guys up to date with my work and thoughts.

*Note: I didn't design the way it currently works, I just inherited it. I would never have written it as it currently is, but trying to get it to work as is was the lesser of evils, or so I thought.*

**Comment by walro** [comment]
We appreciate your hard work!

> If you or your team have any ideas for how to make working with SSL certificates easier, I would love to hear them. No matter what, though, I believe we're going to have to stage the environment in some way prior to running the JVM, as the JVM does not like us messing with trust stores and certs from within the JVM (gee, I wonder why it wouldn't like that...).

Unfortunately I don't have any ideas, but it sounds reasonable to me that you'd need to do some setup before running the tests. Maybe some other @twingly/dev has an idea though?

**Comment by walro** [comment]
I suppose you have already thought of it, but have you peeked at the other ports of VCR? See **Ports in Other Languages** in https://github.com/vcr/vcr/blob/cdf670fc12ada7682966bc3f76bd471efba1eafe/README.md maybe one of the other languages "suffers/suffered" from the same MITM problem? I understand that reading multiple implementations in other languages might not be the first thing to try though, but maybe one can get lucky browsing older issues or what not.

**Comment by cowboygneox** [comment]
Closing as this is no longer relevant.

**Pull request closed without merging**
