### PR TITLE
Updated PR from master sub-branch

### PR DESCRIPTION
**Pull request by xSAVIKx**
I've merged your changes with my documentation changes, so this master_pr branch contains all your changed to README.md and points your travis-ci also.

### CODE REVIEW

**Comment by walro** [comment]
Ok, README is better, now it's just the matter of the weird looking history. I think what we proposed here: https://github.com/twingly/twingly-search-api-java/pull/11#issuecomment-193188520 could work (you'd need to force push too). Maybe you could squash commits and force push to make things look tidier, but I am uncertain as you merge:d our changes pretty late.

**Comment by xSAVIKx** [comment]
ah.
I've tried to make correct rebase with squash, but had no luck :-(

**Comment by walro** [comment]
Any progress? If you are unable to workout the needed git magic you could re-fork and apply your changes manually and submit a new PR from a fresh repository.

**Comment by xSAVIKx** [comment]
Nope, but I'm on holiday today, as I've written.

**Comment by walro** [comment]
Alright, have a nice holiday!

**Comment by xSAVIKx** [comment]
I've cleaned-up commits history in my master branch, so now I'll create new PR branch and submit new PR from that one

**Pull request closed without merging**
