### PR TITLE
Introduced QueryBuilder

### PR DESCRIPTION
**Pull request by xSAVIKx**
It looks that I've rebased also smth that shoud not be rebased....
Looks like 96419a1 commit had been also rebased

### CODE REVIEW

**Comment by dentarg** [comment]
Hey @xSAVIKx 

Looking at https://github.com/xSAVIKx/twingly-search-api-java/tree/upstream_pr it says "This branch is 6 commits ahead, 2 commits behind twingly:master."

You should first get your branch up-to-date with https://github.com/twingly/twingly-search-api-java and the apply your changes. It's okay if you make one big commit with all the QueryBuilder stuff. 

Though we still want the fix for https://github.com/twingly/twingly-search-api-java/issues/10 in it's own commit. Would be great if you put that in a separate pull request.

Let me know how it goes or if you have any questions.

**Comment by xSAVIKx** [comment]
> Looking at https://github.com/xSAVIKx/twingly-search-api-java/tree/upstream_pr it says "This branch is 6 commits ahead, 2 commits behind twingly:master."
@dentarg 
I see that message, but all changes are already in repo. and your commits are also there, please check branch [commits history](https://github.com/xSAVIKx/twingly-search-api-java/commits/upstream_pr)

**Comment by xSAVIKx** [comment]
And I think it's currently not possible to get my fork in normal state (up-to-date) without messing up in git commits history.
Cause I need to merge with your master and cannot than squash commits, cause we need info about merge, so that git knows, that everything is up-to-date.
It's my vision of current situation.

**Comment by dentarg** [comment]
> I see that message, but all changes are already in repo. and your commits are also there, please check branch commits history

The missing commits are:

* https://github.com/twingly/twingly-search-api-java/commit/c9de572c9e77db3c904381964fdc02cf41e5fde7 "Merge pull request #8 from xSAVIKx/master"
* https://github.com/twingly/twingly-search-api-java/commit/1e465dde6602dc5b4ca8010a81f6fb7a2fb961c9 "update version to v.1.0.0" (your branch have this commit but it has a different hash)

> And I think it's currently not possible to get my fork in normal state (up-to-date)

It is.

Do this

```console
git remote add twingly git@github.com:twingly/twingly-search-api-java.git

git co -t twingly/master -b a-new-branch

git push origin a-new-branch
```

Now https://github.com/xSAVIKx/twingly-search-api-java/tree/a-new-branch will be based on https://github.com/twingly/twingly-search-api-java/commits/master

> without messing up in git commits history.

I think we need to forget about your history here.

You need to start over in this new branch, and manually apply your Query Builder changes. Also, when you do this, please don't bump the version to 1.0.1, as we haven't released anything yet. And then open a new pull request.

Please do another pull request with the fix for #10.

**Comment by xSAVIKx** [comment]
ok, so I'll just create new branch and copy there new changes, firstly for QueryBuilder and than for #10.

**Comment by dentarg** [comment]
Yes, and try to think through the changes so you don't accidentally overwrite anything new :) 

And: no need to bump the version to 1.0.1, and as said, put the fix for #10 in it's own branch and pull request.

**Pull request closed without merging**
