### PR TITLE
Introduced QueryBuilder approach

### PR DESCRIPTION
**Pull request by xSAVIKx**
Added QueryBuilder for easier query creation.
Query is now just POJO and all functionality is now in Client impl.
Brought back @Unroll test for query string building.
added support for .properties file, that is now used by both gradle and Java for getting current versions.

### CODE REVIEW

**Comment by walro** [comment]
Hi @xSAVIKx,

We'll need you to re-submit the PR, I think you forgot to rebase with our master before you did your changes. You have duplicated commits and our README changes are gone.

I think you could create a branch on your repository with your current master's state and then rewind your master to the commit before your changes. Rebase your master with our's and then cherry pick your commits from your temporary branch to your master and then re-submit the PR. Or, to make it even better, you can create a branch which you submit the PR from to keep your master clean.

**Comment by xSAVIKx** [comment]
You asked to make rebase - I've done rebase, so all my new changes have overwritten your changes (cause there was refactoring in readme).
And there are duplicated commits due to rebase.

**Comment by xSAVIKx** [comment]
And your changes are in place, except URLs in Readme (check .travis.yml, for example)

**Comment by walro** [comment]
Ok, I think terminology problems here, I meant that your fork was out of sync with our master before you started with your work.

**Comment by walro** [comment]
When I said rebase I meant sync like this: https://robots.thoughtbot.com/keeping-a-github-fork-updated

**Comment by xSAVIKx** [comment]
Yeap, I've done that.
I've done rebase on your repo.

**Comment by walro** [comment]
Ok, let's stop focusing on the word rebase and lets focus on the problem we're seeing now. :) You did changes to the README before synching our latest changes. All of our changes in the README are now gone.

If we step back a bit, not doing any rebase/resync/whatever-you-wanna-call it would lead to a merge conflict when submitting the PR. So what we want is a PR that is based on our current master.

**Comment by xSAVIKx** [comment]
OK :-)

**Pull request closed without merging**
